Resolve CMS-377 "Cms frontend ci cd"

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,7 +1,21 @@
-include:
-  - project: 'a10179/cicd-pipelines'
-    file:
-      - '/templates-stable/.node-ci-template.yml'
+# Define the default image to use for all jobs.
+image: node:20.10.0-alpine
+
+services:
+  # docker in docker service
+  - name: docker:dind
+    # explicitly disable tls to avoid docker startup interruption
+    command: [ "--tls=false" ]
+
+variables:
+  # Instruct Testcontainers to use the daemon of DinD, use port 2735 for non-tls connections.
+  DOCKER_HOST: "tcp://docker:2375"
+  # Instruct Docker not to start over TLS.
+  DOCKER_TLS_CERTDIR: ""
+  # Improve performance with overlayfs.
+  DOCKER_DRIVER: overlay2
+  # Assign which kubernetes agent to use
+  KUBE_CONTEXT: a10179/kubernetes-agent:kubernetes-agent
 
 stages:
   - build
@@ -12,10 +26,317 @@ stages:
   - containerize
   - deploy
 
+.before_script:
+  get_tool:
+    # Check which package manager to use
+    - |
+      if [ -e pnpm-lock.yaml ]; then
+        export tool=npm
+      elif [ -e package-lock.json ]; then
+        export tool=npm
+      elif [ -e yarn.lock ]; then
+        export tool=npm
+      fi
+    - echo "Using $tool"
+    # Cjeck if the tool is installed, if not install it
+    #- if [ "$tool" != "npm" ] && [ "$tool" != "yarn" ]; then npm install -g $tool; fi
+  parse_version:
+    - apk update && apk add jq
+      # Parse version from package.json, trim the quotes and assign it to PARSE_VERSION
+    - |
+      PARSE_VERSION=$(jq '. | .version' package.json | tr -d '"')
+      export PARSE_VERSION
+
+      VAR=${PARSE_VERSION//-*/}
+      export VAR
+
+      TICKET_ID=$(echo "$CI_COMMIT_REF_NAME" | sed 's/\([A-Z-]*-[0-9]*\).*/\1/' | tr '[:upper:]' '[:lower:]')
+      export TICKET_ID
+
+      if [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
+        VERSION="$VAR-beta";
+        export VERSION;
+        jq '.version = "'"${VERSION}"'"' package.json > temp.json && mv temp.json package.json;
+        DOCKER_TAG="$CI_REGISTRY_IMAGE:$VERSION";
+        export DOCKER_TAG;
+        POD_NAME="$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME";
+        export POD_NAME;
+        APP_VERSION="$VERSION-beta";
+        export APP_VERSION;
+      elif [ "$CI_COMMIT_REF_NAME" = "master" ]; then
+        VERSION="$VAR";
+        export VERSION;
+        jq '.version = "'"${VERSION}"'"' package.json > temp.json && mv temp.json package.json;
+        DOCKER_TAG="$CI_REGISTRY_IMAGE:$VERSION";
+        export DOCKER_TAG;
+        POD_NAME="$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME";
+        export POD_NAME;
+        APP_VERSION="$VERSION";
+        export APP_VERSION;
+      elif expr "$CI_COMMIT_REF_NAME" : ".*hotfix.*" > /dev/null ; then
+        VERSION="$VAR-hf";
+        export VERSION;
+        jq '.version = "'"${VERSION}"'"' package.json > temp.json && mv temp.json package.json;   
+        DOCKER_TAG="$CI_REGISTRY_IMAGE:$VERSION-$TICKET_ID";
+        export DOCKER_TAG;
+        POD_NAME="$CI_PROJECT_NAME-$TICKET_ID";
+        export POD_NAME;
+        APP_VERSION="$VERSION-snapshot-$TICKET_ID";
+        export APP_VERSION;
+      else
+        VERSION="$VAR-beta";
+        export VERSION;
+        DOCKER_TAG="$CI_REGISTRY_IMAGE:$VERSION-$TICKET_ID";
+        export DOCKER_TAG;
+        POD_NAME="$CI_PROJECT_NAME-$TICKET_ID";
+        export POD_NAME;
+        APP_VERSION="$VERSION-beta-$TICKET_ID";
+        export APP_VERSION;
+      fi
+
+  npmrc-get:
+    # The publish will fail if the package name and version combination already exists in the registry.
+    # npmrc configuration for the npm package registry
+    - echo "@blueai:registry=https://gitlab.com/api/v4/groups/a10179/-/packages/npm/" >> .npmrc
+    - echo "//gitlab.com/api/v4/groups/a10179/-/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
+    - echo "legacy-peer-deps=true" >> .npmrc
+    # Disable git checks to avoid gitlab ci pipeline failure
+    - echo "git-checks=false" >> .npmrc
+
+  npmrc-publish:
+    # The publish will fail if the package name and version combination already exists in the registry.
+    # npmrc configuration for the npm package registry
+    - echo "@blueai:registry=https://gitlab.com/api/v4/groups/a10179/-/packages/npm/" > .npmrc
+    - echo "//gitlab.com/api/v4/groups/a10179/-/packages/npm/:_authToken=${NPM_READ_TOKEN}" >> .npmrc
+    - echo "always-auth=true" >> .npmrc
+    # Disable git checks to avoid gitlab ci pipeline failure
+    - echo "git-checks=false" >> .npmrc
+    - cat .npmrc
+build:
+  image: node:18-alpine
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: always 
+    - when: manual
+  allow_failure: false
+  stage: build
+  before_script:
+    - !reference [.before_script, get_tool]
+    - !reference [.before_script, parse_version]
+    - !reference [.before_script, npmrc-get]
+    - apk add git
+  script:
+    - $tool install
+    - $tool run build
+  timeout: 5min
+  artifacts:
+    paths:
+      - dist/
+
+version-check:
+  image: node:18-alpine
+  needs:
+    - job: build
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: always
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+      when: never
+    - when: manual
+  allow_failure: false
+  stage: version-check
+  before_script:
+    - !reference [.before_script, parse_version]
+    - apk add git
+  script:
+    - |
+      if [ "$CI_COMMIT_REF_NAME" = "develop" ] || [ "$CI_COMMIT_REF_NAME" = "master" ] || [ "$CI_COMMIT_REF_NAME" = "staging" ]; then
+        CHECK=$(git tag -l "$VERSION" || true);
+        export CHECK
+        if [ -n "$CHECK" ]; then
+          echo "Version $VERSION already exists, exiting..."
+          exit 1
+        else
+          echo "Version $VERSION does not exist, continuing..."
+          exit 0
+        fi
+      else
+        CHECK=$(git tag -l "$PARSE_VERSION" || true);
+        export CHECK
+        if [ -n "$CHECK" ]; then
+          echo "Version $PARSE_VERSION already exists, exiting..."
+          exit 1
+        else
+          echo "Version $PARSE_VERSION does not exist, continuing..."
+          exit 0
+        fi
+      fi
+  timeout: 5min
+
+sonarqube-check:
+  when: manual
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+  needs:
+    - job: build
+  image:
+    name: sonarsource/sonar-scanner-cli:latest
+    entrypoint: [""]
+  variables:
+    # Disable the shallow clone, so that sonarqube can get the full history.
+    GIT_DEPTH: "0"
+  stage: sonarqube-check
+  before_script:
+    - apk add gettext
+    - envsubst < sonar-project.properties.template > sonar-project.properties
+  script:
+    - sonar-scanner
+  allow_failure: true
+  after_script:
+    # Get the sonarqube metrics and severities using the sonarqube api, parse the json using jq, and print the results.
+    - |
+      apk add jq curl
+      curl -u $SONAR_RESULTS_TOKEN: "$SONAR_METRICS_API?component=$SONAR_PROJECT_KEY&branch=$CI_COMMIT_BRANCH&$SONAR_METRICKEYS" | jq '.c.measures'
+      curl -u $SONAR_RESULTS_TOKEN: "$SONAR_SEVERITIES_API?componentKeys=$SONAR_PROJECT_KEY&branch=$CI_COMMIT_BRANCH&$SONAR_SEVERITIESKEY" | jq '.facets'
+  timeout: 5min
+
+package:
+  stage: package
+  image: node:20.10.0-alpine
+  needs:
+    - job: build
+      artifacts: true
+    - job: version-check
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: on_success
+    - if: $CI_COMMIT_BRANCH =~ /hotfix*/
+      when: manual
+    - when: never
+  before_script:
+    - !reference [.before_script, get_tool]
+    - !reference [.before_script, parse_version]
+    - !reference [.before_script, npmrc-publish]
+  script:
+    # Check npm configuration (logs)
+    - npm config list -l
+    - jq '. | .version' package.json | tr -d '"'
+    # Save the version to variable.env file
+    - echo "VERSION=$VERSION" > variables.env
+    - echo "PARSE_VERSION=$PARSE_VERSION" >> variables.env
+    # Publish the package to the npm registry
+    - $tool publish
+  timeout: 5min
+  artifacts:
+    reports:
+      # This job will create a file called variables.env
+      dotenv: variables.env
+
+build-docker-image:
+  stage: containerize
+  needs:
+    # If mvn-package job fails, this job will be skipped
+    - job: build
+      artifacts: true
+  image: docker:latest
+  rules:
+    - if: $CI_COMMIT_TAG
+      when: never
+    - if: $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "staging" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: on_success
+    - if: $CI_COMMIT_BRANCH =~ /hotfix*/
+      when: manual
+    - when: manual
+  services:
+    - docker:dind
+  before_script:
+    - !reference [.before_script, parse_version]
+    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
+  script:
+    - echo $DOCKER_TAG
+    - docker build --build-arg NPM_READ_TOKEN="${NPM_READ_TOKEN}" -f Dockerfile.ci -t $DOCKER_TAG .
+    - docker push $DOCKER_TAG
+    - echo "VERSION=$VERSION" > variables.env
+    - echo "PARSE_VERSION=$PARSE_VERSION" >> variables.env
+    - echo "DOCKER_TAG=$DOCKER_TAG" >> variables.env
+    - echo "APP_VERSION=$APP_VERSION" >> variables.env
+  artifacts:
+    reports:
+      # This job will create a file called variables.env
+      dotenv: variables.env
+
+tag_release:
+  stage: release
+  image: alpine:latest
+  needs:
+    - job: build
+      artifacts: true
+      optional: true
+    - job: package
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME == "master"
+      when: never
+    - if: $CI_COMMIT_TAG || $CI_COMMIT_BRANCH == "master"
+      when: never
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: on_success
+    - if: $CI_COMMIT_BRANCH == "staging"
+      when: on_success
+    - if: $CI_COMMIT_BRANCH =~ /hotfix*/
+      when: manual
+    - when: never
+  before_script:
+    - !reference [.before_script, parse_version]
+    - apk add git
+  script:
+    - git config --global user.name "RELEASE_TOKEN"
+    - git config --global user.email $RELEASE_TOKEN_EMAIL@noreply.gitlab.com
+    - git remote set-url origin "https://RELEASE_TOKEN:$RELEASE_TOKEN@gitlab.com/$CI_PROJECT_PATH.git"
+    - git checkout $CI_COMMIT_BRANCH
+    - git tag -a $VERSION -m "Release $VERSION"
+    - git push --follow-tags -o ci.skip
+  timeout: 5min
+
+release:
+  stage: release
+  image: registry.gitlab.com/gitlab-org/release-cli:latest
+  needs:
+    - job: package
+      artifacts: true
+  rules:
+    # If branch name is not master, this job will be skipped
+    - if: $CI_COMMIT_BRANCH == "master"
+      when: on_success
+  before_script:
+    - !reference [.before_script, parse_version]
+    - apk add git
+  script:
+    - git config --global user.name "RELEASE_TOKEN"
+    - git config --global user.email $RELEASE_TOKEN_EMAIL@noreply.gitlab.com
+    - git remote set-url origin "https://RELEASE_TOKEN:$RELEASE_TOKEN@gitlab.com/$CI_PROJECT_PATH.git"
+    - git checkout $CI_COMMIT_BRANCH
+    - git add . && git commit -m "$PARSE_VERSION -> $VERSION"
+    - git push --follow-tags -o ci.skip
+  # add pushing commits to master
+    - echo "running release_job for version $VERSION"
+  release:
+    # This job will create a release on gitlab
+    name: '$VERSION'
+    description: 'Created using the release-cli'
+    tag_name: '$VERSION'
+    ref: '$CI_COMMIT_SHA'
+
 .deploy:
   create_tls:
     - export SECRET_NAME="$CI_PROJECT_NAME-tls"
-    - apt update && apt install -y openssl
+    - apk add openssl
     - |
         if kubectl get secret $SECRET_NAME --namespace=$NAMESPACE &> /dev/null; then
             echo "Secret $SECRET_NAME already exists. Skipping creation."
@@ -27,6 +348,7 @@ stages:
                 --key=$CI_PROJECT_NAME.key \
                 --namespace=$NAMESPACE
         fi
+
   deploy_to_environment:
     - echo $DOCKER_TAG
     - echo $APP_VERSION
@@ -64,9 +386,9 @@ stages:
                   fi
               fi
           fi
-      elif [ -f ./deployments/delpoyment.tmpl ]; then
-        envsubst < ./deployment/deployment.tmpl > ./deployment/deployment.yaml
-        kubectl apply -f ./deployment/deployment.yaml
+      elif [ -f ./deployments/deployment.tmpl ]; then
+        envsubst < ./deployments/deployment.tmpl > ./deployments/deployment.yaml
+        kubectl apply -f ./deployments/deployment.yaml
         kubectl rollout restart deployment "${CI_PROJECT_NAME}" -n "$NAMESPACE"
         if kubectl rollout status deployment "${CI_PROJECT_NAME}" -n "$NAMESPACE" --timeout=300s; then
           echo "Deployment succeeded"
@@ -95,6 +417,7 @@ deploy-to-develop:
     NAMESPACE: $CI_PROJECT_NAME-develop
     VITE_APP_PREFIX: ${VITE_APP_PREFIX}
     VITE_APP_API_BASE_URL: ${VITE_APP_API_BASE_URL}
+    HOST: cms.develop.rdev.antwerptechnologies.com
   image:
     # Use helm and kubectl image
     name: dtzar/helm-kubectl:3.13
@@ -110,7 +433,7 @@ deploy-to-develop:
   before_script:
     # This job needs the before_script from .kube-requirments to run
     - if [ -n "$KUBE_CONTEXT" ]; then kubectl config use-context "$KUBE_CONTEXT"; fi
-    # - !reference [.deploy, create_tls]
+    - !reference [.deploy, create_tls]
   script:
     - !reference [.deploy, deploy_to_environment]
 
@@ -126,6 +449,7 @@ deploy-to-qa:
     NAMESPACE: $CI_PROJECT_NAME-qa
     VITE_APP_PREFIX: ${VITE_APP_PREFIX}
     VITE_APP_API_BASE_URL: ${VITE_APP_API_BASE_URL}
+    HOST: cms.qa.rdev.antwerptechnologies.com
   image:
     # Use helm and kubectl image
     name: dtzar/helm-kubectl:3.13
@@ -141,7 +465,7 @@ deploy-to-qa:
   before_script:
     # This job needs the before_script from .kube-requirments to run
     - if [ -n "$KUBE_CONTEXT" ]; then kubectl config use-context "$KUBE_CONTEXT"; fi
-    # - !reference [.deploy, create_tls]
+    - !reference [.deploy, create_tls]
   script:
     - !reference [.deploy, deploy_to_environment]
 
@@ -157,6 +481,7 @@ deploy-to-dev:
     NAMESPACE: dev-shour
     VITE_APP_PREFIX: ${VITE_APP_PREFIX}
     VITE_APP_API_BASE_URL: ${VITE_APP_API_BASE_URL}
+    HOST: 'cms.${NAMESPACE}.rdev.antwerptechnologies.com'
   image:
     # Use helm and kubectl image
     name: dtzar/helm-kubectl:3.13
@@ -172,6 +497,6 @@ deploy-to-dev:
   before_script:
     # This job needs the before_script from .kube-requirments to run
     - if [ -n "$KUBE_CONTEXT" ]; then kubectl config use-context "$KUBE_CONTEXT"; fi
-    # - !reference [.deploy, create_tls]
+    - !reference [.deploy, create_tls]
   script:
     - !reference [.deploy, deploy_to_environment]
